DROP TABLE IF EXISTS users, locations, category, events, compilations, participations, comments, events_compilations;

CREATE TABLE IF NOT EXISTS users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255)       NOT NULL,
    email    VARCHAR(512)       NOT NULL CONSTRAINT unique_email UNIQUE
);

CREATE TABLE IF NOT EXISTS locations (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat      REAL               NOT NULL,
    lon      REAL               NOT NULL
);

CREATE TABLE IF NOT EXISTS category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)     NOT NULL   CONSTRAINT unique_name UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation    VARCHAR(2000) NOT NULL,
    category_id   BIGINT        NOT NULL
    CONSTRAINT fk_events_category REFERENCES category ON DELETE CASCADE ON UPDATE CASCADE,
    confirmed_requests BIGINT,
    created_on    TIMESTAMP     NOT NULL,
    description   VARCHAR(7000) NOT NULL,
    event_date    TIMESTAMP     NOT NULL,
    initiator_id  BIGINT        NOT NULL
    CONSTRAINT fk_events_users REFERENCES users ON DELETE CASCADE ON UPDATE CASCADE,
    location_id   BIGINT        NOT NULL
    CONSTRAINT fk_events_locations REFERENCES locations ON DELETE CASCADE ON UPDATE CASCADE,
    paid          boolean       NOT NULL,
    participant_limit BIGINT    NOT NULL,
    published_on   TIMESTAMP,
    request_moderation boolean  NOT NULL,
    state         VARCHAR(15),
    title         VARCHAR(120)  NOT NULL,
    views         BIGINT        NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned        boolean       NOT NULL,
    title         VARCHAR(120)  NOT NULL  CONSTRAINT unique_title UNIQUE
);

CREATE TABLE IF NOT EXISTS participations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created       TIMESTAMP     NOT NULL,
    event         BIGINT        NOT NULL REFERENCES events (id) ON DELETE CASCADE ON UPDATE CASCADE,
    requester     BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    status        VARCHAR(100)  NOT NULL
);

 CREATE TABLE IF NOT EXISTS comments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text         VARCHAR(10000) NOT NULL,
    event_id     BIGINT         NOT NULL    CONSTRAINT fk_comments_events REFERENCES events ON DELETE CASCADE ON UPDATE CASCADE,
    author_id    BIGINT         NOT NULL    CONSTRAINT fk_comments_users REFERENCES users ON DELETE CASCADE ON UPDATE CASCADE,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_on TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS events_compilations (
    event_id       BIGINT        NOT NULL   REFERENCES events (id),
    compilation_id BIGINT        NOT NULL   REFERENCES compilations (id),
    CONSTRAINT pk_events_compilations PRIMARY KEY (event_id, compilation_id)
);